export const navigationLinks = [
  {
    name: "Panel General",
    url: "/dashboard",
    "aria-label": "Go to Dashboard",
    title: "Dashboard",
    type: "private",
  },
  {
    name: "Panel de Venta",
    url: "/dashboard/pos",
    "aria-label": "Go to POS",
    title: "Point of Sale",
    type: "private",
  },
  {
    name: "Cadetes",
    url: "/dashboard/routes",
    "aria-label": "Go to Routes",
    title: "Route Management",
    type: "private",
  },
  {
    name: "Rendiciones",
    url: "/dashboard/settlement",
    "aria-label": "Go to Settlements",
    title: "Driver Settlements",
    type: "private",
  },
  {
    name: "Cuentas de Deudores",
    url: "/dashboard/accounts-receivable",
    "aria-label": "Go to Accounts Receivable",
    title: "Accounts Receivable Management",
    type: "private",
  },
  {
    name: "Historial de Ventas",
    url: "/dashboard/sales-history",
    "aria-label": "Ver historial de ventas",
    title: "Historial de ventas",
    type: "private",
  },
  {
    name: "Panel administrativo",
    url: "/dashboard/admin/dashboard",
    title: "Panel administrativo",
    "aria-label": "Panel de administrador",
    type: "private",
    permissions: "ADMIN",
  },
  {
    name: "Inicia sesión",
    url: "/auth/login",
    type: "public",
  },
];
